name: CI Pipeline

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code from dev branch
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Run tests
      - name: Run tests
        run: |
          mkdir -p test-results
          npm test -- --reporter mocha-junit-reporter --reporter-options mochaFile=./test-results/results.xml

      - name: test results pubish
        uses: actions/upload-artifact@v4.6.2
        if:  always()
        with:
          name: test-results-artifact
          path: test-results/results.xml

      - name: run code quality using eslink(jave script framework)
        run: |
          set -o pipefail
          npx eslint . --ext .js --exit-on-fatal-error -f stylish | tee lint-report.txt

      - name: code quality publish
        if: always()
        uses: actions/upload-artifact@v4.6.2
        with:
          name: code-quality-artifact
          path: lint-report.txt

      - name : dependency
          npm audit --audit-level=high --json > npm-audit-report.json

      - name: vul
        if: always()
        uses: actions/upload-artifact@v4.6.2
        with:
          name: code-dependency-artifact
          path: npm-audit-report.json

          
          
      

        
